#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use ZBH::SGE;
use ZBH::Local;
use ZBH::Flensburg;

use Config::Simple;
use Log::Log4perl;

sub main {
  my $file = shift;
  Log::Log4perl->init(shift);

  my $config = new Config::Simple($file);
  my $logger = Log::Log4perl->get_logger("35buildgraph");

  my $process = "$FindBin::Bin/start";
  if ( ZBH::Local::is_background_process( $process ) ) {
    $logger->error( "Already started: ", $process );
    return ("wait");
  }
    
  my $sequence_graph = $config->param("35buildgraph.sequence_graph");
  $logger->info( "35buildgraph.sequence_graph: ", $sequence_graph );
    
  my $structure_graph = $config->param("35buildgraph.structure_graph");
  $logger->info( "35buildgraph.structure_graph: ", $structure_graph );
    
  if (ZBH::Local::is_file_exists( $sequence_graph )
    and ZBH::Local::is_file_exists( $structure_graph )) {
      $logger->info( "Sequence_graph found: ", $sequence_graph );
      $logger->info( "Structure_graph found: ", $structure_graph );
      $logger->info( "Done");
      return ("done");
  }
    
  my $sequence_imbiss = $config->param("35buildgraph.sequence_imbiss");
  $logger->info( "35buildgraph.sequence_imbiss: ", $sequence_imbiss );    
  
  my $structure_imbiss = $config->param("35buildgraph.structure_imbiss");
  $logger->info( "35buildgraph.structure_imbiss: ", $structure_imbiss );    
  
  if (ZBH::Local::is_file_exists( $sequence_imbiss )
    and ZBH::Local::is_file_exists( $structure_imbiss )) {
      $logger->info( "Sequence_imbiss found: ", $sequence_imbiss );
      $logger->info( "Structure_imbiss found: ", $structure_imbiss );
      $logger->info( "Ready");
      return ("ready");
  }

  $logger->fatal( "Can not start task, can not find imbiss files: $sequence_imbiss, $structure_imbiss" );
  return ("error");
}

exit( 
  not print( 
    main( 
      "$FindBin::Bin/../../etc/update.conf", 
      "$FindBin::Bin/../../etc/logging.conf" ,
    ) 
  ) 
);
