#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Config::Simple;

sub main {
	my $config1 = shift;

	my $cfg = new Config::Simple($config1);

	my $starter = $cfg->param("bin.starter");


#	system("nohup $starter1 $graph1 $cluster1 >/dev/null 2>&1 &");
#	system("nohup $starter2 $graph2 $cluster2 >/dev/null 2>&1 &");

	return "underconstruction";
}

exit(
	print(
		main(
			"$FindBin::Bin/../../etc/cluster/cluster1.cnf",
			"$FindBin::Bin/../../etc/cluster/cluster2.cnf"
		)
	)
);

