#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use ZBH::SGE;
use ZBH::Local;
use Config::Simple;
use ZBH::Flensburg;

sub main {
    my $file = shift;

    my $config  = new Config::Simple($file);

    my $starter = $config->param("bin.starter");
    if ( not ZBH::Local::is_file_exists($starter)) {
      ZBH::Flensburg::fatal( "10buildvec",  "Can not start task", 
	"Executalbe file not found: $starter");
      return("wait");
    }	
    
    my $status  = $config->param("bin.status");
    if ( not ZBH::Local::is_file_exists($status)) {
      ZBH::Flensburg::fatal( "10buildvec",  "Can not start task", 
	"Executalbe file not found: $status");
      return("wait");
    }	
    
    my $result = ZBH::Local::execute("$status");
    if ( $result eq "started" ) {
      return ("wait") ;
    }
    
    if ( $result eq "done" ) {
      my $todayrun = time;
      my $lastrun  = $config->param("settings.lastrun");
      my $interval = $config->param("settings.interval");
      if ( ( $todayrun - $lastrun ) > $interval ) {
	      return ("ready");
      }
      return ("done");
    }
    return ("ready");
}
exit( not print( main("$FindBin::Bin/../../etc/vector.cnf") ) );

