#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Getopt::Lucid qw( :all );
use Config::Simple;

sub file_exists {
	my $file = shift;
	return ( ( -d $file ) || ( -e $file ) );
}


sub check_background_process {
	my $file = shift;

	return 0;
}

sub is_background_process_sge {
	my $file    = shift;
	my $cfg     = new Config::Simple($file);
	my $starter = $cfg->param("bin.starter");
	my $name    = substr( $starter, rindex( $starter, "/" ) + 1 );

	my $result = `qstat -r -ext`;

	return ( index( $result, $name ) > -1 );
}

sub main {
	my $config = shift;

	if (   check_background_process($config)
		|| is_background_process_sge($config) )
	{
		return "wait";
	}

	return "done";
}
exit( print( main( "$FindBin::Bin/../../etc/vector/vectors.cnf", ) ) );

