#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Getopt::Lucid qw( :all );
use Config::Simple;

use lib "/home/pool/other/wurst/salamiServer/v02";
use Salamisrvini;
use lib $LIB_LIB;     #initialize in local Salamisrvini.pm;
use lib $LIB_ARCH;    #initialize in local Salamisrvini.pm;
use vars qw ( $INPUT_CLST_LIST $OUTPUT_BIN_DIR $PDB_TOP_DIR $OUTPUT_LIB_LIST);

#
#
#
sub main {
	my $config = shift;

	my $cfg = new Config::Simple($config);

	$cfg->param( "background.updated",  time() );
	$cfg->param( "planner.library",     $OUTPUT_LIB_LIST );
	$cfg->param( "planner.cluster",     "$FindBin::Bin/../../var/vector/clusters90.txt" );
	$cfg->param( "planner.source",      $PDB_TOP_DIR );
	$cfg->param( "planner.temp",        "$FindBin::Bin/../../var/vector/tmp" );
	$cfg->param( "planner.output_bin",  "$FindBin::Bin/../../var/vectorbin" );
	$cfg->param( "planner.output_vec1", "$FindBin::Bin/../../var/vectorvec1" );
	$cfg->param( "planner.output_vec2", "$FindBin::Bin/../../var/vector/vec2" );
	$cfg->param( "planner.class_vec1",  $CLASSFILE );
	$cfg->param( "planner.class_vec2",  $CA_CLASSFILE );
	$cfg->param( "planner.output_list", "$FindBin::Bin/../../var/vector/pdb_all.list" );
	$cfg->write($config);

	return "done";
}

exit( print( main("$FindBin::Bin/../../etc/vector/buildvec.cnf") ) );

