#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Getopt::Lucid qw( :all );
use Config::Simple;

sub main {
	my $config1 = shift;
	my $config2 = shift;

	# TODO: notify maintainer about wrong config
	# write xml for salami rss server
	# and send it over ssh to flensburg
	return "done";
}
exit(
	print(
		main(
			"$FindBin::Bin/../../etc/vector/vector.cnf",
		)
	)
);
