#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Getopt::Lucid qw( :all );
use Config::Simple;

sub check_config {
	my $file = shift;

	my @specs = ( Param("--config")->default($file) );
	my $opt   = Getopt::Lucid->getopt( \@specs );
	$opt->validate( { 'requires' => [] } );
	my $cfg = new Config::Simple( $opt->get_config );

	my $current = time();
	my $updated = $cfg->param("background.updated");
	if ( $updated && ( $current - $updated ) < ( 60 * 60 * 12 ) ) {
		return 1;
	}
	return 0;
}

my $config = "$FindBin::Bin/../../etc/salami/buildvec.cnf";
if ( check_config($config) ) {
	exit( print('done') );
}
exit( print('ready') )
