#!/usr/bin/python3
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
import os 
import sys
import logging
from logging.handlers import RotatingFileHandler

from optparse import OptionParser

root = os.path.dirname(os.path.realpath(__file__))

sys.path.append("%s/lib/python" % root)

from que.queue import Queue

if __name__ == "__main__":
    parser = OptionParser()
    parser.add_option("-q", "--queue", action="store_true", default=False, dest="queue", help="show tasks")
    parser.add_option("-t", "--task", default=None, dest="task", help="run task by name")
    parser.add_option("-l", "--loglevel", default=logging.INFO, dest="loglevel", help="logging level")
    parser.add_option("-f", "--logfile", default=("%s/log/update.log" % root), dest="logfile", help="file to store log records")

    (options, args) = parser.parse_args()

    format = '[%(relativeCreated)d][%(name)s] %(levelname)s - %(message)s'
    logging.basicConfig( level=options.loglevel, format=format)

    handler = RotatingFileHandler(filename=options.logfile, maxBytes=(1024 * 100000), backupCount=3)
    handler.setFormatter(logging.Formatter(format))

    logger = logging.getLogger('queue')
    logger.addHandler(handler)      
      
    queue = Queue(logger, "%s/update.d/*" % root)
    queue.queue() if options.queue \
        else queue.start(options.task)
