#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use FindBin;
use lib "$FindBin::Bin/../../lib";
use ZBH::SGE;
use ZBH::Local;
use ZBH::Flensburg;
use Config::Simple;
use Log::Log4perl;

sub main {

  my $config = new Config::Simple(shift);
  Log::Log4perl->init(shift);
  my $config_structure = shift;  
  my $config_sequence = shift;
  my $starter = shift;  
  
  my $date = time;
  
  my $logger  = Log::Log4perl->get_logger("25buildimbiss");

  my $result_sequence = $config->param( "25buildimbiss.sequence");
  $logger->info("25buildimbiss.sequence: ", $result_sequence);
  
  my $result_structure = $config->param( "25buildimbiss.structure");
  $logger->info("25buildimbiss.structure: ", $result_structure);

  if (ZBH::Local::is_file_exists($result_sequence)) {
    $logger->info("Remove file: ", $result_sequence);
    unlink($result_sequence);
  }
  
  if (ZBH::Local::is_file_exists($result_structure)) {
    $logger->info("Remove file: ", $result_structure);
    unlink($result_structure);
  }
  
  $logger->info("Config_sequence: ", $config_sequence);
  if (not ZBH::Local::is_file_exists($config_sequence)) {
    $logger->fatal("Can not start task, can not find config file: $config_sequence");
    return ("error");
  }

  $logger->info("Config_structure: ", $config_structure);
  if (not ZBH::Local::is_file_exists($config_structure)) {
    $logger->fatal("Can not start task, can not find config file: $config_structure");
    return ("error");
  }

  if (not ZBH::Local::is_file_exists($starter)) {
    $logger->fatal("Can not start task, can not find config file: $starter");
    return ("error");
  }

  $logger->info("Start: $starter $config_sequence $result_sequence");
  system("qsub -S /bin/bash -wd $FindBin::Bin $starter $config_sequence $result_sequence");
  
  $logger->info("Start: $starter $config_structure $result_structure");
  system("qsub -S /bin/bash -wd $FindBin::Bin $starter $config_structure $result_structure");

  my $flensburg = ZBH::Flensburg->new($logger);
  $flensburg->info("25buildimbiss", "Task starter report",
    "Started: $starter $config_sequence $result_sequence\n".
    "Started: $starter $config_structure $result_structure\n"
  );

  return ("wait");
}

exit( 
  not print( 
    main( 
      "$FindBin::Bin/../../etc/update.conf", 
      "$FindBin::Bin/../../etc/logging.conf",
      "$FindBin::Bin/../../etc/25buildimbiss.str.conf",
      "$FindBin::Bin/../../etc/25buildimbiss.seq.conf",
      "$FindBin::Bin/wurstimbiss.sh",
    ) 
  ) 
);
