#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use v5.10;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use ZBH::SGE;
use ZBH::Local;
use ZBH::Flensburg;

use Config::Simple;
use Log::Log4perl;


sub fatal($ $) {
  my $logger = shift;
  my $message = shift;
  
  $logger->fatal($message);
  ZBH::Flensburg::fatal("25buildimbiss", "Can not start task", $message);  
}

sub main {
  my $file = shift;
  Log::Log4perl->init(shift);
  my $config_structure = shift;  
  my $config_sequence = shift;
  my $seqlog = shift;
  my $strlog = shift;

  my $config  = new Config::Simple($file);
  my $logger  = Log::Log4perl->get_logger("25buildimbiss");
  
  my $result_sequence = $config->param( "25buildimbiss.sequence");
  $logger->info( "25buildimbiss.sequence: ", $result_sequence );
  
  my $result_structure = $config->param( "25buildimbiss.structure");	
  $logger->info( "25buildimbiss.structure: ", $result_structure );

  my $process  = "wurstimbiss";
  if (ZBH::Local::is_background_process($process) 
    or ZBH::SGE::is_background_process_sge($process)) {
      $logger->error( "Already started: ", $process );
      return("wait");
  }	  
  
  my $sequences = $config->param("25buildimbiss.sequences");
  $logger->info( "25buildimbiss.sequences: ", $sequences );
  
  $logger->info( "Config_structure: ", $config_structure );
  if ( not ZBH::Local::is_file_exists($config_structure)) {
    fatal($logger, "Can not find config file: $config_structure");
    return("error");
  }

  $logger->info( "Config_sequence: ", $config_sequence );
  if ( not ZBH::Local::is_file_exists($config_sequence)) {
    fatal($logger, "Can not find config file: $config_sequence");
    return("error");
  }
  
  if ( not ZBH::Local::is_file_exists($sequences)) {
    fatal($logger, "Can not start task, can not find sequence list: $sequences");
    return("error");
  }
	
	
  if (ZBH::Local::is_file_exists($result_sequence) 
    and ZBH::Local::is_file_exists($result_structure)) {

      if (ZBH::Local::is_file_exists($seqlog) 
	and ZBH::Local::is_file_exists($strlog)) { 
	
	  my $keystring = /Done:\s*100.*/;
	  # If result files are here and log files are here
	  # and task is 100% finished, send done status
	  if(ZBH::SGE::is_background_process_done($seqlog, $keystring) 
	    and ZBH::SGE::is_background_process_done($strlog, $keystring)) {
	      $logger->info( "Remove logfile: ", $seqlog);
	      $logger->info( "Remove logfile: ", $strlog);
	      
	      unlink($seqlog);
	      unlink($strlog);
	      	      
	      $logger->info( "Done");
	      return ("done");
	  }
	  # If result files are here and log files are here
	  # but task was not 100 % finished and there are no
	  # sge background taks to finish it restart task
	  $logger->info( "Ready");
	  return("ready");
	}
    # If there are a result files but no log files
    # we can be sure task is finished bacause 
    # we remove log files only here in this script
    $logger->info( "Done");
    return ("done");
  }
    
  $logger->info( "Ready");
  return ("ready");
}

exit( 
  not print( 
    main( 
      "$FindBin::Bin/../../etc/update.conf", 
      "$FindBin::Bin/../../etc/logging.conf" ,
      "$FindBin::Bin/../../etc/25buildimbiss.str.conf",
      "$FindBin::Bin/../../etc/25buildimbiss.seq.conf",
      "$FindBin::Bin/../../log/25buildimbiss.seq.log",
      "$FindBin::Bin/../../log/25buildimbiss.str.log"
    ) 
  ) 
);

