#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use ZBH::SGE;
use ZBH::Local;
use ZBH::Flensburg;

use Config::Simple;
use Log::Log4perl;

sub main {
	my $file    = shift;
	my $logging = shift;

	my $server  = shift;
	my $planner = shift;
	my $worker  = shift;

	Log::Log4perl->init($logging);
	my $logger = Log::Log4perl->get_logger("50diagrams");

	my $config = new Config::Simple($file);

	my $cath_eval = $config->param("cath.eval");
	my $scop_eval = $config->param("scop.eval");
	my $pdb50_eval = $config->param("pdb50.eval");
	my $pdb90_eval = $config->param("pdb90.eval");
	my $salami_eval = $config->param("salami.eval");


	return ("wait");
}

exit(
	not print(
		main(
			"$FindBin::Bin/../../etc/50diagrams.conf",
			"$FindBin::Bin/../../etc/logging.conf"
		  )
	)
);
