#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Config::Simple;
use ZBH::Flensburg;
use ZBH::SGE;

sub main {
	my $file = shift;

	my $config = new Config::Simple($file);

	my $sequence_imbiss  = $config->param("sequence.imbiss");
	my $structure_imbiss = $config->param("structure.imbiss");

	my $task_error = "";

	$task_error .= "Can not find data file: $sequence_imbiss\n"
	  if ( !ZBH::SGE::is_file_exists($sequence_imbiss) );

	$task_error .= "Can not find data file: $structure_imbiss\n"
	  if ( !ZBH::SGE::is_file_exists($structure_imbiss) );

	ZBH::Flensburg::fatal( 
		"30configgraph", 
		"Config-checker report",
		$task_error );

	return ("wait");
}

exit( print( main( "$FindBin::Bin/../../etc/graph.cnf", ) ) );
