#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Config::Simple;

sub main {
	my $config1 = shift;
	my $config2 = shift;

	my $cfg1 = new Config::Simple($config1);
	my $cfg2 = new Config::Simple($config2);

	$cfg1->param( "sources.imbiss", "/home/stud2013/ovoroshylov/Clustering/wurst-background/var/imbiss/aacid.csv");
	$cfg2->param( "sources.imbiss", "/home/stud2013/ovoroshylov/Clustering/wurst-background/var/imbiss/salami.csv");

	$cfg1->write($config1);
	$cfg2->write($config2);

	return "done";
}

exit(
	print(
		main(
			"$FindBin::Bin/../../etc/graph/grapha.cnf",
			"$FindBin::Bin/../../etc/graph/graphs.cnf"
		)
	)
);

