#!/usr/bin/perl
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Config::Simple;

sub main {
	my $config1 = shift;
	my $config2 = shift;

	my $cfg1 = new Config::Simple($config1);
	my $cfg2 = new Config::Simple($config2);

	$cfg1->param( "sources.imbiss", "/home/stud2013/ovoroshylov/Clustering/wurst-background/var/imbiss/aacid.csv");
	$cfg2->param( "sources.imbiss", "/home/stud2013/ovoroshylov/Clustering/wurst-background/var/imbiss/salami.csv");

	$cfg1->write($config1);
	$cfg2->write($config2);

	return "done";
}

exit(
	print(
		main(
			"$FindBin::Bin/../../etc/graph/grapha.cnf",
			"$FindBin::Bin/../../etc/graph/graphs.cnf"
		)
	)
);

