#!/usr/bin/perl
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Getopt::Lucid qw( :all );
use Config::Simple;

sub check_config {
	my $file = shift;

	my @specs = ( Param("--config")->default($file) );
	my $opt   = Getopt::Lucid->getopt( \@specs );
	$opt->validate( { 'requires' => [] } );
	my $cfg = new Config::Simple( $opt->get_config );

	my $imbiss = $cfg->param("sources.imbiss");
	if ( !( ( -d $imbiss ) || ( -e $imbiss ) ) ) {
		return 0;
	}

#	my $graph = $cfg->param("sources.graph");
#	if ( ( ( -d $graph ) || ( -e $graph ) ) ) {
#		return 0;
#	}
	return 1;
}

my $config1 = "$FindBin::Bin/../../etc/graph/grapha.cnf";
my $config2 = "$FindBin::Bin/../../etc/graph/graphs.cnf";

if ( !check_config($config1) || !check_config($config2) ) {
	exit( print('ready') );
}
exit( print('done') );
