#!/usr/bin/perl
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Getopt::Lucid qw( :all );
use Config::Simple;

sub file_exists {
	my $file = shift;
	return ( ( -d $file ) || ( -e $file ) );
}

sub is_config_correct {
	my $file = shift;
	my $cfg  = new Config::Simple($file);
	return file_exists( $cfg->param("sources.imbiss") );
}

sub main {
	my $config1 = shift;
	my $config2 = shift;

	if ( !is_config_correct($config1) || !is_config_correct($config2) ) {
		return "ready";
	}
	return "done";
}
exit(
	print(
		main(
			"$FindBin::Bin/../../etc/graph/grapha.cnf",
			"$FindBin::Bin/../../etc/graph/graphs.cnf"
		)
	)
);
