#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Getopt::Lucid qw( :all );
use Config::Simple;

sub file_exists {
	my $file = shift;
	return ( ( -d $file ) || ( -e $file ) );
}

sub is_config_correct {
	my $file = shift;
	my $cfg  = new Config::Simple($file);
	return file_exists( $cfg->param("sources.imbiss") );
}

sub main {
	my $config1 = shift;
	my $config2 = shift;

	if (   !is_config_correct($config1)
		|| !is_config_correct($config2) )
	{
		return "ready";
	}
	return "done";
}
exit(
	print(
		main(
			"$FindBin::Bin/../../etc/graph/graph1.cnf",
			"$FindBin::Bin/../../etc/graph/graph2.cnf"
		)
	)
);
