#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Getopt::Lucid qw( :all );
use Config::Simple;

sub main {
	my $config1 = shift;
	my $config2 = shift;

	my $cfg1 = new Config::Simple($config1);
	my $cfg2 = new Config::Simple($config2);

	my $imbiss1 = $cfg1->param("sources.imbiss");
	my $imbiss2 = $cfg2->param("sources.imbiss");

	my $graph1 = $cfg1->param("sources.graph");
	my $graph2 = $cfg2->param("sources.graph");

	my $first;

	open( INPUT, "<$imbiss1" ) or die "Could not open '$imbiss1' $!\n";
	open( GRAPH, '>', "$graph1" );
	$first = 1;
	while ( my $line = <INPUT> ) {
		chomp $line;
		if ( $first == 1 ) {
			$first = 0;
			next;
		}
		my @fields = split ";", $line;

		my $seq1       = $fields[2];
		my $seq2       = $fields[3];
		my $similarity = $fields[10];    # get sequence identity
		print GRAPH "$seq1\t$seq2\t$similarity\n";
	}
	close(GRAPH);
	close(INPUT);

	open( INPUT, "<$imbiss2" ) or die "Could not open '$imbiss2' $!\n";
	open( GRAPH, '>', "$graph2" );
	$first = 1;
	while ( my $line = <INPUT> ) {
		chomp $line;
		if ( $first == 1 ) {
			$first = 0;
			next;
		}
		my @fields = split ";", $line;

		my $seq1       = $fields[2];
		my $seq2       = $fields[3];
		my $similarity = $fields[4];    # get tm score
		print GRAPH "$seq1\t$seq2\t$similarity\n";
	}
	close(GRAPH);
	close(INPUT);
	
	return "done";
}

my $root = "$FindBin::Bin/../..";

exit(
	print(
		main(
			"$root/etc/graph/graph1.cnf",
			"$root/etc/graph/graph2.cnf"
		)
	)
);

