#!/usr/bin/perl
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Config::Simple;

sub file_exists {
	my $file = shift;
	return ( ( -d $file ) || ( -e $file ) );
}

sub is_input_exists {
	my $file = shift;

	my $cfg = new Config::Simple($file);

	return file_exists( $cfg->param("sources.imbiss") );
}

sub is_output_exists {
	my $file = shift;
	my $cfg  = new Config::Simple($file);
	return file_exists( $cfg->param("sources.graph") );
}

sub main {
	my $config1 = shift;
	my $config2 = shift;

	if ( is_output_exists($config1) && is_output_exists($config2) ) {
		return "done";
	}

	if ( is_input_exists($config1) && is_input_exists($config2) ) {
		return "ready";
	}
}

exit(
	print(
		main(
			"$FindBin::Bin/../../etc/graph/grapha.cnf",
			"$FindBin::Bin/../../etc/graph/graphs.cnf"
		)
	)
);
