#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Config::Simple;

sub file_exists {
	my $file = shift;
	return ( ( -d $file ) || ( -e $file ) );
}

sub is_input_exists {
	my $file = shift;

	my $cfg = new Config::Simple($file);

	return file_exists( $cfg->param("sources.imbiss") );
}

sub is_output_exists {
	my $file = shift;
	my $cfg  = new Config::Simple($file);
	return file_exists( $cfg->param("sources.graph") );
}

sub main {
	my $config1 = shift;
	my $config2 = shift;

	if ( is_output_exists($config1) && is_output_exists($config2) ) {
		return "done";
	}

	if ( is_input_exists($config1) && is_input_exists($config2) ) {
		return "ready";
	}
}

exit(
	print(
		main(
			"$FindBin::Bin/../../etc/graph/graph1.cnf",
			"$FindBin::Bin/../../etc/graph/graph2.cnf"
		)
	)
);
