#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Config::Simple;
use ZBH::SGE;
use ZBH::Local;
use File::Basename;

sub main {
	my $file   = shift;
	my $config = new Config::Simple($file);

	if ( ZBH::Local::is_background_process( dirname(__FILE__).'/start' ) ) {
		return ("wait");
	}
	
	return ("done")
	  if ( ZBH::Local::is_file_exists( $config->param("sequence.graph") )
		&& ZBH::Local::is_file_exists( $config->param("structure.graph") ) );

	return ("ready")
	  if ( ZBH::Local::is_file_exists( $config->param("sequence.imbiss") )
		&& ZBH::Local::is_file_exists( $config->param("structure.imbiss") ) );

	return ("wait");
}

exit( print( main( "$FindBin::Bin/../../etc/graph.cnf", ) ) );
