#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use ZBH::SGE;
use ZBH::Local;
use Config::Simple;
use ZBH::Flensburg;

sub main {
    my $file   = shift;
    my $config = new Config::Simple($file);

    my $process = "$FindBin::Bin/start";
    if ( ZBH::Local::is_background_process( $process ) ) {
      return ("wait");
    }
    
    my $sequence_graph = $config->param("sequence.graph");
    my $structure_graph = $config->param("structure.graph");
    if (ZBH::Local::is_file_exists( $sequence_graph )
	and ZBH::Local::is_file_exists( $structure_graph )) {
	  return ("done");
    }
    
    my $sequence_imbiss = $config->param("sequence.imbiss");
    my $structure_imbiss = $config->param("structure.imbiss");
    if (ZBH::Local::is_file_exists( $sequence_imbiss )
	and ZBH::Local::is_file_exists( $structure_imbiss )) {
	  return ("ready");
    }

    ZBH::Flensburg::fatal( "25buildimbiss",  "Can not start task", 
      "Can not find imbiss files: $sequence_imbiss, $structure_imbiss");
    
    return ("wait");
}

exit( not print( main( "$FindBin::Bin/../../etc/graph.cnf", ) ) );
