#!/usr/bin/perl

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Config::Simple;

sub main {
	my $config1 = shift;
	my $config2 = shift;
	my $cfg1    = new Config::Simple($config1);
	my $cfg2    = new Config::Simple($config2);

	$cfg1->param( "sources.graph","/home/stud2013/ovoroshylov/Clustering/wurst-background/var/graph/aacid.ncol");
	$cfg2->param( "sources.graph", "/home/stud2013/ovoroshylov/Clustering/wurst-background/var/graph/salami.ncol");

	$cfg1->param( "sources.cluster", "/home/stud2013/ovoroshylov/Clustering/wurst-background/var/cluster/aacid.clust");
	$cfg2->param( "sources.cluster", "/home/stud2013/ovoroshylov/Clustering/wurst-background/var/cluster/salami.clust");

	$cfg1->write($config1);
	$cfg2->write($config2);

	return "done";
}

exit(
	print(
		main(
			"$FindBin::Bin/../../etc/cluster/clustera.cnf",
			"$FindBin::Bin/../../etc/cluster/clusters.cnf"
		)
	)
);

