#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Config::Simple;
use ZBH::Flensburg;
use ZBH::SGE;

sub main {
	my $file = shift;

	my $config = new Config::Simple($file);

	my $sequence_graph  = $config->param("sequence.graph");
	my $structure_graph = $config->param("structure.graph");
	my $script_status   = $config->param("bin.status");
	my $script_starter  = $config->param("bin.starter");

	my $task_error = "";

	$task_error .= "Can not find data file: $sequence_graph\n"
	  if ( !ZBH::SGE::is_file_exists($sequence_graph) );

	$task_error .= "Can not find data file: $structure_graph\n"
	  if ( !ZBH::SGE::is_file_exists($structure_graph) );

	$task_error .= "Can not find script file: $script_status\n"
	  if ( !ZBH::SGE::is_file_exists($script_status) );

	$task_error .= "Can not find script file: $script_starter\n"
	  if ( !ZBH::SGE::is_file_exists($script_starter) );

	ZBH::Flensburg::fatal( 
		"40configcluster", 
		"Config-checker report",
		"$task_error\n" 
			. "Check your config file: $file"
	);

	return ("wait");
}

exit( print( main( "$FindBin::Bin/../../etc/cluster.cnf", ) ) );
