#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use File::Path qw( make_path );

use Config::Simple;
use ZBH::Flensburg;
use ZBH::SGE;
use ZBH::Local;

sub main {
	my $file = shift;
	my $response = undef;

	my $config = new Config::Simple($file);

	my $alphabet = $config->param("sources.alphabet");
	if(not ZBH::Local::is_file_exists( $alphabet )) {
	  ZBH::Flensburg::fatal( "11buildseq", "Task starter report",
	    "Can not find alphabet file: $alphabet" );
	  return ("wait");
	}
	
	my $vector_folder = $config->param("vector.folder");
	my $vector_collection = $config->param("vector.collection");
	if(not ZBH::Local::is_folder_exists( $vector_folder )) {
	  ZBH::Flensburg::fatal( "11buildseq", "Task starter report",
	    "Vector folder does not exists: $vector_folder" );
	  return ("wait");
	}

	# Find all vector files
	# and store it to some file
	ZBH::Local::execute("find $vector_folder -name '*.vec' > $vector_collection");
	# Convert vectors to sequences
	# using some alphabet generated from Steve Hoffman
	my $convertor = "$FindBin::Bin/convertprobvec.x";
	if(not ZBH::Local::is_file_exists( $convertor )) {
	  ZBH::Flensburg::fatal( "11buildseq", "Can not start task",
	    "Binary file not found: $convertor" );
	  return ("wait");
	}
	
	ZBH::Local::execute("$convertor -f $vector_collection -a $alphabet");	

	my $sequence_folder = $config->param("sequence.folder");
	my $sequence_collection = $config->param("sequence.collection");
	# Move al sequence files to 
	# different sequence folder
 	if (not ZBH::Local::is_folder_exists($sequence_folder) ) {
 	    make_path($sequence_folder);
	    if(not ZBH::Local::is_folder_exists( $sequence_folder )) {
	      ZBH::Flensburg::fatal( "11buildseq", "Task starter report",
		"Vector folder does not exists: $sequence_folder" );
	      return ("wait");
	    } 	
	}	
	
	ZBH::Local::execute("find $vector_folder -type f -iname '*.seq' -exec mv -t $sequence_folder {} \+");	
	ZBH::Local::execute("find $sequence_folder -name '*.seq' > $sequence_collection");	

 	ZBH::Flensburg::success( "11buildseq", "Task starter report",
	    "Generated files: $vector_collection started at: $sequence_collection"
 	);

	return ("wait");
}

exit( not print( main("$FindBin::Bin/../../etc/buildseq.cnf") ) );
