#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Getopt::Lucid qw( :all );
use Config::Simple;
use ZBH::Local;

sub main {
	my $file = shift;

	my $config  = new Config::Simple($file);

	my $alphabet = $config->param("sources.alphabet");
	if(!ZBH::Local::is_file_exists( $alphabet)) {
		ZBH::Flensburg::fatal( "11buildseq", "Task starter report",
			"Can not find alphabet file: $alphabet"
		);
		return ("wait")
	}

	return ("done")
	  if ( ZBH::Local::is_file_exists( $config->param("vector.collection") )
		&& ZBH::Local::is_file_exists( $config->param("sequence.collection") ) );

	return ("ready");
}

exit( not print( main("$FindBin::Bin/../../etc/buildseq.cnf") ) );

