#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Config::Simple;

sub main {
	my $config = shift;

	my $cfg = new Config::Simple($config);

	my $cluster1 = $cfg->param("sources.cluster1");
	my $cluster2 = $cfg->param("sources.cluster2");

	my $graph1 = $cfg->param("sources.graph1");
	my $graph2 = $cfg->param("sources.graph2");

	my $result = $cfg->param("sources.result");
	my $starter = $cfg->param("bin.starter");

	system("nohup $starter $graph1 $graph2 $cluster1 $cluster2 > $result 2>&1 &");

	return "done";
}

exit( print( main("$FindBin::Bin/../../etc/merge/merge.cnf") ) );
