#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Config::Simple;

sub file_exists {
	my $file = shift;
	return ( ( -d $file ) || ( -e $file ) );
}

sub is_config_correct {
	my $file = shift;

	my $cfg = new Config::Simple($file);

	if ( !file_exists( $cfg->param("bin.startera") ) ) {
		return 0;
	}

	if ( !file_exists( $cfg->param("bin.starters") ) ) {
		return 0;
	}

	if ( !file_exists( $cfg->param("sources.grapha") ) ) {
		return 0;
	}

	if ( !file_exists( $cfg->param("sources.graphs") ) ) {
		return 0;
	}

	if ( !file_exists( $cfg->param("sources.clustera") ) ) {
		return 0;
	}

	if ( !file_exists( $cfg->param("sources.clusters") ) ) {
		return 0;
	}

	if ( !file_exists( $cfg->param("sources.resulta") ) ) {
		return 0;
	}

	if ( !file_exists( $cfg->param("sources.results") ) ) {
		return 0;
	}

	return 1;
}

sub main {
	my $config = shift;

	if ( !is_config_correct($config) ) {
		exit( print('ready') );
	}

	return "done";
}

exit( print( main("$FindBin::Bin/../../etc/merge/merge.cnf") ) );

