#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.use strict;
use warnings;

use FindBin;

use lib "$FindBin::Bin/../../lib/perl";
use Config::Simple;

sub file_exists {
	my $file = shift;
	return ( ( -d $file ) || ( -e $file ) );
}

# TODO: check is process runned local
sub is_background_process {
	my $file = shift;

	return 0;
}

sub is_background_process_sge {
	my $file    = shift;
	my $cfg     = new Config::Simple($file);
	my $starter = $cfg->param("bin.starter");
	my $name    = substr( $starter, rindex( $starter, "/" ) + 1 );

	my $result = `qstat -r -ext`;

	return ( index( $result, $name ) > -1 );
}


sub is_config_correct {
	my $file = shift;

	my $cfg = new Config::Simple($file);

	if ( !file_exists( $cfg->param("bin.starter") ) ) {
		return 0;
	}

	if ( !file_exists( $cfg->param("sources.graph1") ) ) {
		return 0;
	}

	if ( !file_exists( $cfg->param("sources.graph2") ) ) {
		return 0;
	}

	if ( !file_exists( $cfg->param("sources.cluster1") ) ) {
		return 0;
	}

	if ( !file_exists( $cfg->param("sources.cluster2") ) ) {
		return 0;
	}

	if ( !file_exists( $cfg->param("sources.result") ) ) {
		return 0;
	}

	return 1;
}

sub main {
	my $config = shift;

	if(is_background_process($config)) {
		return "wait";
	}

	if ( !is_config_correct($config) ) {
		return "ready";
	}

	return "done";
}

my $root = "$FindBin::Bin/../..";
exit( print( main("$root/etc/merge/merge.cnf") ) );

