#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use ZBH::SGE;
use ZBH::Local;
use ZBH::Flensburg;
use Config::Simple;

sub main {
	my $file = shift;
	my $date = time;

	my $config = new Config::Simple($file);
	
	my $result_sequence = $config->param( "result.sequence");
	my $result_structure = $config->param( "result.structure");

	if (ZBH::Local::is_file_exists($result_sequence)) {
	  unlink($result_sequence);
	}
	
	if (ZBH::Local::is_file_exists($result_structure)) {
	  unlink($result_structure);
	}
	
	my $config_sequence = "$FindBin::Bin/etc/sequence.cnf";
	if (not ZBH::Local::is_file_exists($config_sequence)) {
	  ZBH::Flensburg::fatal( "25buildimbiss",  "Can not start task", 
	    "Can not find config file: $config_sequence");
	  return ("wait");
	}

	my $config_structure = "$FindBin::Bin/etc/structure.cnf";
	if (not ZBH::Local::is_file_exists($config_structure)) {
	  ZBH::Flensburg::fatal( "25buildimbiss",  "Can not start task", 
	    "Can not find config file: $config_structure");
	  return ("wait");
	}

	my $starter = "$FindBin::Bin/wurstimbiss.sh";
	if (not ZBH::Local::is_file_exists($starter)) {
	  ZBH::Flensburg::fatal( "25buildimbiss",  "Can not start task", 
	    "Can not find config file: $starter");
	  return ("wait");
	}

 	system("qsub -S /bin/bash -wd $FindBin::Bin $starter $config_sequence $result_sequence");
 	system("qsub -S /bin/bash -wd $FindBin::Bin $starter $config_structure $result_structure");

	ZBH::Flensburg::info( "25buildimbiss", "Task starter report",
	  "Started: $starter $config_sequence $result_sequence\n".
	  "Started: $starter $config_structure $result_structure\n"
	);

	return ("wait");
}

exit( not print( main( "$FindBin::Bin/../../etc/wurstimbiss.cnf", ) ) );
