#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Config::Simple;
use ZBH::SGE;
use ZBH::Flensburg;

sub main {
	my $file = shift;
	my $date = time;

	my $config = new Config::Simple($file);
	$config->param( "settings.lastrun", $date );
	$config->write($file);

	my $starter = $config->param("bin.starter");

	system("nohup $starter >/dev/null 2>&1 &");

	ZBH::Flensburg::success(
		"25buildimbiss",
		"Task starter report",
		"Script: $starter started at: $date "
	);

	return ("wait");
}

exit( print( main( "$FindBin::Bin/../../etc/imbiss.cnf", ) ) );
