#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Config::Simple;
use ZBH::SGE;
use ZBH::Flensburg;

sub main {
	my $file = shift;
	my $date = time;

	my $config = new Config::Simple($file);
	
	my $result_sequence = $config->param( "result.sequence");
	my $result_structure = $config->param( "result.structure");
	
	unlink($result_sequence);
	unlink($result_structure);
		
	system("qsub -S /bin/bash -wd $FindBin::Bin $FindBin::Bin/wurstimbiss.sh $FindBin::Bin/etc/sequence.cnf $result_sequence");
	system("qsub -S /bin/bash -wd $FindBin::Bin $FindBin::Bin/wurstimbiss.sh $FindBin::Bin/etc/structure.cnf $result_structure");

	ZBH::Flensburg::info( "25buildimbiss", "Task starter report",
		"Started: $FindBin::Bin/wurstimbiss.sh $FindBin::Bin/etc/sequence.cnf $result_sequence\n".
		"Started: $FindBin::Bin/wurstimbiss.sh $FindBin::Bin/etc/structure.cnf $result_structure\n"
	);

	return ("wait");
}

exit( not print( main( "$FindBin::Bin/../../etc/wurstimbiss.cnf", ) ) );
