#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Getopt::Lucid qw( :all );
use Config::Simple;
use ZBH::SGE;
use ZBH::Local;

sub main {
	my $file = shift;

	my $config  = new Config::Simple($file);

	return("wait") if (
		ZBH::SGE::is_background_process_sge("wurstimbiss")
		|| ZBH::Local::is_background_process("wurstimbiss")
	);

	# Check is all tasks successfully 
	# finished and there are results
	return ("done") if ( 
		ZBH::SGE::is_background_process_done( "$FindBin::Bin/../../log/sequence.log", "100.000000 %" )
		&& ZBH::SGE::is_background_process_done( "$FindBin::Bin/../../log/structure.log", "100.000000 %" ) );

	return ("ready");
}

exit( not print( main( "$FindBin::Bin/../../etc/wurstimbiss.cnf", ) ) );

