#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use ZBH::SGE;
use ZBH::Local;
use Config::Simple;
use ZBH::Flensburg;

sub main {
	my $file = shift;

	my $config  = new Config::Simple($file);
	
	my $result_sequence = $config->param( "result.sequence");
	my $result_structure = $config->param( "result.structure");	

	my $process  = "wurstimbiss";
	if (ZBH::Local::is_background_process($process) 
	  or ZBH::SGE::is_background_process_sge($process)) {
	  return("wait");
	}	
	
	my $sequences = $config->param("requirements.sequences");
	if ( not ZBH::Local::is_file_exists($sequences)) {
	  ZBH::Flensburg::fatal( "25buildimbiss",  "Can not start task", 
	    "Can not find sequence list: $sequences");
	  return("wait");
	}
	
	if (ZBH::Local::is_file_exists($result_sequence) 
	    and ZBH::Local::is_file_exists($result_structure)) {
	      my $keystring = "100.000000 %";
	      my $seqlog = "$FindBin::Bin/../../log/sequence.log";
	      my $strlog = "$FindBin::Bin/../../log/structure.log";
	      if(ZBH::SGE::is_background_process_done($seqlog, $keystring) 
		  and ZBH::SGE::is_background_process_done($strlog, $keystring)) {
		    unlink($seqlog);
		    unlink($strlog);
		    return ("done");
	      }
	      return("wait");
	}	

	return ("ready");
}

exit( not print( main( "$FindBin::Bin/../../etc/wurstimbiss.cnf", ) ) );

