#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Config::Simple;
use ZBH::Flensburg;
use ZBH::SGE;

sub main {
	my $file = shift;

	my $config = new Config::Simple($file);

	my $script_status   = $config->param("bin.status");
	my $script_starter  = $config->param("bin.starter");
	my $script_exporter = $config->param("bin.exporter");

	my $string_error = "";
	$string_error .= "Can not find script file: $script_status\n"
	  if ( !ZBH::SGE::is_file_exists($script_status) );

	$string_error .= "Can not find script file: $script_starter\n"
	  if ( !ZBH::SGE::is_file_exists($script_starter) );

	$string_error .= "Can not find script file: $script_exporter\n"
	  if ( !ZBH::SGE::is_file_exists($script_exporter) );

	ZBH::Flensburg::fatal( 
		"20configimbiss", 
		"Config-checker report",
		$string_error );

	return ("wait");
}

exit( print( main( "$FindBin::Bin/../../etc/imbiss.cnf", ) ) );
