#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Getopt::Lucid qw( :all );
use Config::Simple;

sub is_config_correct {
	my $file = shift;

	my $cfg = new Config::Simple($file);

	my $structlist = $cfg->param("sources.structlist");
	if ( !( ( -d $structlist ) || ( -e $structlist ) ) ) {
		return 0;
	}

	my $sequencelist = $cfg->param("sources.sequencelist");
	if ( !( ( -d $sequencelist ) || ( -e $sequencelist ) ) ) {
		return 0;
	}
	my $substitution = $cfg->param("sources.substitution");
	if ( !( ( -d $substitution ) || ( -e $substitution ) ) ) {
		return 0;
	}

	my $alphabet1 = $cfg->param("sources.alphabet");
	if ( !( ( -d $alphabet1 ) || ( -e $alphabet1 ) ) ) {
		return 0;
	}
	my $logger1 = $cfg->param("sources.logger");
	if ( !( ( -d $logger1 ) || ( -e $logger1 ) ) ) {
		return 0;
	}

	my $binarypath1 = $cfg->param("sources.binarypath");
	if ( !( ( -d $binarypath1 ) || ( -e $binarypath1 ) ) ) {
		return 0;
	}

	my $pdbpath1 = $cfg->param("sources.pdbpath");
	if ( !( ( -d $pdbpath1 ) || ( -e $pdbpath1 ) ) ) {
		return 0;
	}

	my $vectorpath1 = $cfg->param("sources.vectorpath");
	if ( !( ( -d $vectorpath1 ) || ( -e $vectorpath1 ) ) ) {
		return 0;
	}

	return 1;
}
sub main {
	my $config1 = shift;
	my $config2 = shift;

	if ( !is_config_correct($config1) || !is_config_correct($config2) ) {
		return "ready";
	}

	return "done";
}

exit(
	print(
		main(
			"$FindBin::Bin/../../etc/imbiss/wurstimbissa.cnf",
			"$FindBin::Bin/../../etc/imbiss/wurstimbisss.cnf"
		)
	)
);

