#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Config::Simple;

sub main {
	my $config1 = shift;
	my $config2 = shift;

	my $cfg1 = new Config::Simple($config1);
	my $cfg2 = new Config::Simple($config2);

	my $starter1 = $cfg1->param("bin.starter");
	my $starter2 = $cfg2->param("bin.starter");

	my $graph1 = $cfg1->param("sources.graph");
	my $graph2 = $cfg2->param("sources.graph");

	my $cluster1 = $cfg1->param("sources.cluster");
	my $cluster2 = $cfg2->param("sources.cluster");

	system("nohup $starter1 $graph1 $cluster1 >/dev/null 2>&1 &");
	system("nohup $starter2 $graph2 $cluster2 >/dev/null 2>&1 &");

	return "done";
}

exit(
	print(
		main(
			"$FindBin::Bin/../../etc/cluster/cluster1.cnf",
			"$FindBin::Bin/../../etc/cluster/cluster2.cnf"
		)
	)
);
