#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Config::Simple;

sub main {
	my $file = shift;

	my $config = new Config::Simple($file);
	$config->param( "settings.lastrun", time );
	$config->write($file);

	my $starter = $config->param("bin.starter");

	my $graph1 = $config->param("sequence.graph");
	my $graph2 = $config->param("structure.graph");

	my $cluster1 = $config->param("sequence.cluster");
	my $cluster2 = $config->param("structure.cluster");

	system("nohup $starter $graph1 $cluster1 >/dev/null 2>&1 &");
	system("nohup $starter $graph2 $cluster2 >/dev/null 2>&1 &");

	return ("wait");
}

exit( print( main( "$FindBin::Bin/../../etc/cluster.cnf", ) ) );
