#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use ZBH::SGE;
use ZBH::Local;
use Config::Simple;
use ZBH::Flensburg;


sub main {
    my $file = shift;

    my $config = new Config::Simple($file);

    my $starter = $config->param("bin.starter");
    if ( not ZBH::Local::is_file_exists($starter)) {
      ZBH::Flensburg::fatal( "45buildcluster",  "Can not start task", 
	"Executalbe file not found: $starter");
      return("wait");
    }	
    
    my $status  = $config->param("bin.status");
    if ( not ZBH::Local::is_file_exists($status)) {
      ZBH::Flensburg::fatal( "45buildcluster",  "Can not start task", 
	"Executalbe file not found: $status");
      return("wait");
    }	
		
    my $sequence_graph = $config->param("sequence.graph");
    my $sequence_cluster = $config->param("sequence.cluster");    
    if ( not ZBH::Local::is_file_exists($sequence_graph)) {
      ZBH::Flensburg::fatal( "45buildcluster",  "Can not start task", 
	"Graph file not found: $sequence_graph");
      return("wait");
    }	

    my $structure_graph = $config->param("structure.graph");
    my $structure_cluster = $config->param("structure.cluster");    
    if ( not ZBH::Local::is_file_exists($structure_graph)) {
      ZBH::Flensburg::fatal( "45buildcluster",  "Can not start task", 
	"Graph file not found: $structure_graph");
      return("wait");
    }	    

    ZBH::Local::background("$starter $sequence_graph $sequence_cluster");
    ZBH::Local::background("$starter $structure_graph $structure_cluster");

    ZBH::Flensburg::info("45buildcluster", "Script starter report",
      "Script: $starter started \n convert graph: $sequence_graph to  cluster: $sequence_cluster \n" . 
      "Script: $starter started \n convert graph: $structure_graph to  cluster: $structure_cluster \n"
    );

    return ("wait");
}

exit( not print( main( "$FindBin::Bin/../../etc/cluster.cnf", ) ) );
