#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use ZBH::SGE;
use ZBH::Local;
use ZBH::Flensburg;

use Config::Simple;
use Log::Log4perl;

sub main {
  my $file = shift;
  Log::Log4perl->init(shift);
  
  my $config = new Config::Simple($file);
  my $logger = Log::Log4perl->get_logger("45buildcluster");

  my $starter = $config->param("45buildcluster.starter");
  $logger->info("45buildcluster.starter: ", $starter);
  if ( not ZBH::Local::is_file_exists($starter)) {
    $logger->fatal("Can not start task, executalbe file not found: $starter");
    return("error");
  }	
  
  my $status  = $config->param("45buildcluster.status");
  $logger->info("45buildcluster.status: ", $status );
  if ( not ZBH::Local::is_file_exists($status)) {
    $logger->fatal("Can not start task, executalbe file not found: $status");
    return("error");
  }	
      
  my $result = ZBH::Local::execute("$status");
  $logger->info("$status: ", $result );
  if ( $result eq "started" ) {
    $logger->error("Already started: ", $status );
    return ("wait") ;
  }	   
  
  my $sequence_graph = $config->param("45buildcluster.sequence_graph");
  $logger->info("45buildcluster.sequence_graph: ", $sequence_graph );
  if ( not ZBH::Local::is_file_exists($sequence_graph)) {
    $logger->fatal("Can not start task, graph file not found: $sequence_graph");
    return("error");
  }	

  my $structure_graph = $config->param("45buildcluster.structure_graph");
  $logger->info("45buildcluster.structure_graph: ", $structure_graph );
  if ( not ZBH::Local::is_file_exists($structure_graph)) {  
    $logger->fatal( "Can not start task, graph file not found: $structure_graph");
    return("error");
  }	    
  
  my $sequence_cluster = $config->param("45buildcluster.sequence_cluster");
  $logger->info("45buildcluster.sequence_cluster: ", $sequence_cluster );
  if ( not ZBH::Local::is_file_exists($structure_graph)) {
    $logger->info("Structure_graph not found: ", $structure_graph );
    $logger->info("Ready");
    return ("ready");
  }

  my $structure_cluster = $config->param("45buildcluster.structure_cluster");
  $logger->info("45buildcluster.structure_cluster: ", $structure_cluster );
  if ( not ZBH::Local::is_file_exists($structure_graph)) {
    $logger->info("Structure_cluster not found: ", $structure_cluster );
    $logger->info("Ready");
    return ("ready");
  }

  $logger->info("Done");
  return ("done");
}

exit( 
  not print( 
    main( 
      "$FindBin::Bin/../../etc/update.conf",
      "$FindBin::Bin/../../etc/logging.conf" ,
    ) 
  ) 
);
