#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib";
use Getopt::Lucid qw( :all );
use Config::Simple;
use ZBH::SGE;
use File::Copy;
use File::Path qw(make_path remove_tree);
use ZBH::Flensburg;
use ZBH::Local;
use File::Basename;
use Log::Log4perl;

sub main {
  my $file = shift;
  Log::Log4perl->init(shift);

  my $config = new Config::Simple($file);
  my $logger = Log::Log4perl->get_logger("60export");

  my $source = $config->param("60export.source");
  if(not ZBH::Local::is_folder_exists( $source )) {
    $logger->fatal( "Task starter report, vector folder does not exists: $source" );
    return ("error");
  } 	    
    
  my $destination = $config->param("60export.destination");
  if(not ZBH::Local::is_folder_exists( $destination )) {
    $logger->fatal("Task starter report, vector folder does not exists: $destination" );
    return ("error");
  } 	    	
	
  $logger->info("Clean folder: $destination" );
  remove_tree("$destination");
  
  $logger->info("Moving files from: $source, to :$destination" );
  move( $source, $destination ) or return ("error");
  
  $logger->info("Create folder: $source" );
  make_path("$source") or return ("error");

  ZBH::Flensburg::success($logger, "60export", "Data exporter report",
    "You can find all files here: $destination"
  );

  return ("done");
}

exit( 
  not print( 
    main( 
      "$FindBin::Bin/../../etc/update.conf", 
      "$FindBin::Bin/../../etc/logging.conf" ,
    ) 
  ) 
);