#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use FindBin;
use lib "$FindBin::Bin/../../lib";
use ZBH::SGE;
use ZBH::Local;
use Config::Simple;
use ZBH::Flensburg;
use Log::Log4perl;


sub main {
  my $file = shift;
  Log::Log4perl->init(shift);

  my $config = new Config::Simple($file);
  my $logger = Log::Log4perl->get_logger("45buildcluster");

  my $worker = "$FindBin::Bin/clustering.sh";
  $logger->info("45buildcluster.worker: ", $worker );
  if ( not ZBH::Local::is_file_exists($worker)) {
    $logger->fatal("Can not start task, executable file not found: $worker");
    return("error");
  }	
  
  if (ZBH::Local::is_background_process($worker)
    ||  ZBH::SGE::is_background_process_sge($worker)) {
      $logger->error("Already started: ", $status );
      return ("wait") ;
  }
    
  my $sequence_graph = $config->param("45buildcluster.sequence_graph");
  $logger->info( "45buildcluster.sequence_graph", $sequence_graph);
  if ( not ZBH::Local::is_file_exists($sequence_graph)) {
    $logger->fatal("Can not start task, graph file not found: $sequence_graph");
    return("error");
  }	
  
  my $sequence_cluster = $config->param("45buildcluster.sequence_cluster");    
  $logger->info( "45buildcluster.sequence_cluster", $sequence_cluster);
  

  my $structure_graph = $config->param("45buildcluster.structure_graph");
  $logger->info( "45buildcluster.structure_graph", $structure_graph);
  if ( not ZBH::Local::is_file_exists($structure_graph)) {
    $logger->fatal("Can not start task, graph file not found: $structure_graph");
    return("error");
  }	    
  
  my $structure_cluster = $config->param("45buildcluster.structure_cluster");    
  $logger->info( "45buildcluster.structure_cluster", $structure_cluster);
  

  $logger->info("Start: $worker $sequence_graph $sequence_cluster");
  ZBH::Local::background("qsub -S /bin/bash -wd $FindBin::Bin $worker $sequence_graph $sequence_cluster");
    
  $logger->info("Start: $worker $structure_graph $structure_cluster");
  ZBH::Local::background("qsub -S /bin/bash -wd $FindBin::Bin $worker $structure_graph $structure_cluster");

  ZBH::Flensburg::info($logger, "45buildcluster", "Script starter report",
    "Script: $worker started \n convert graph: $sequence_graph to  cluster: $sequence_cluster \n" . 
    "Script: $worker started \n convert graph: $structure_graph to  cluster: $structure_cluster \n"
  );

  return ("wait");
}

exit( 
  not print( 
    main( 
      "$FindBin::Bin/../../etc/update.conf",
      "$FindBin::Bin/../../etc/logging.conf" ,
    ) 
  ) 
);
