#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib";
use ZBH::SGE;
use ZBH::Local;
use ZBH::Flensburg;

use Config::Simple;
use Log::Log4perl;

sub fatal($ $) {
  my $logger = shift;
  my $message = shift;
  
  $logger->fatal($message);
  ZBH::Flensburg::fatal($logger, "45buildcluster", "Can not start task", $message);  
}

sub main {
  my $file = shift;
  Log::Log4perl->init(shift);
  
  my $config = new Config::Simple($file);
  my $logger = Log::Log4perl->get_logger("45buildcluster");
      
  my $worker = "$FindBin::Bin/clustering.sh";
  $logger->info("45buildcluster.worker: $worker" );
  if ( not ZBH::Local::is_file_exists($worker)) {
    fatal($logger, "Can not start task, executable file not found: $worker");
    return("error");
  }	
  
  if (ZBH::Local::is_background_process($worker)
    ||  ZBH::SGE::is_background_process_sge($worker)) {
      $logger->error("Already started: $worker" );
      return ("wait") ;
  }
    
  my $sequence_graph = $config->param("45buildcluster.sequence_graph");
  $logger->info("45buildcluster.sequence_graph: ", $sequence_graph );
  if ( not ZBH::Local::is_file_exists($sequence_graph)) {
    fatal($logger, "Can not start task, graph file not found: $sequence_graph");
    return("error");
  }	

  my $structure_graph = $config->param("45buildcluster.structure_graph");
  $logger->info("45buildcluster.structure_graph: $structure_graph" );
  if ( not ZBH::Local::is_file_exists($structure_graph)) {  
    fatal($logger, "Can not start task, graph file not found: $structure_graph");
    return("error");
  }	    
  
  my $sequence_cluster = $config->param("45buildcluster.sequence_cluster");
  $logger->info("45buildcluster.sequence_cluster: ", $sequence_cluster );
  if ( not ZBH::Local::is_file_exists($sequence_cluster)) {
    $logger->info("Structure_graph not found: $sequence_cluster");
    $logger->info("Ready");
    return ("ready");
  }

  my $structure_cluster = $config->param("45buildcluster.structure_cluster");
  $logger->info("45buildcluster.structure_cluster: ", $structure_cluster );
  if ( not ZBH::Local::is_file_exists($structure_cluster)) {
    $logger->info("Structure_cluster not found: ", $structure_cluster );
    $logger->info("Ready");
    return ("ready");
  }

  $logger->info("Done");
  return ("done");
}

exit( 
  not print( 
    main( 
      "$FindBin::Bin/../../etc/update.conf",
      "$FindBin::Bin/../../etc/logging.conf" ,
    ) 
  ) 
);
