#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use Config::Simple;
use ZBH::Flensburg;
use ZBH::SGE;

sub main {
	my $file = shift;

	my $config = new Config::Simple($file);

	my $exporter         = $config->param("bin.exporter");
	my $result_sequence  = $config->param("result.sequence");
	my $result_structure = $config->param("result.structure");

	unlink( $result_sequence, $result_structure );

	system("$exporter $result_sequence $result_structure");

	ZBH::Flensburg::success(
		"26exportimbiss",
		"Data exporter report",
		"Script: $exporter\n"
		  . "Data exported to: $result_sequence\n"
		  . "Data exported to: $result_structure\n"
	);

	return ("done");
}

exit( not print( main( "$FindBin::Bin/../../etc/imbiss.cnf", ) ) );
