#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib/perl";
use ZBH::SGE;
use ZBH::Local;
use Config::Simple;
use ZBH::Flensburg;


sub main {
    my $file = shift;

    my $config = new Config::Simple($file);
    
    my $source = $config->param("result.source");
    if(not ZBH::Local::is_folder_exists( $source )) {
      ZBH::Flensburg::fatal( "60export", "Task starter report",
	"Vector folder does not exists: $source" );
      return ("wait");
    } 	    
    
    my $destination = $config->param("result.destination");
    if(not ZBH::Local::is_folder_exists( $destination )) {
      ZBH::Flensburg::fatal( "60export", "Task starter report",
	"Vector folder does not exists: $destination" );
      return ("wait");
    } 	    

    my $process = "$FindBin::Bin/start";
    if ( ZBH::Local::is_background_process( $process ) ) {
      return ("wait");
    }

    if(ZBH::Local::is_folder_empty($source)
      and not ZBH::Local::is_folder_empty($destination)) {
	return ("done");
    }
    
    if(ZBH::Local::is_folder_exists($source)
	and not ZBH::Local::is_folder_empty($source)) {
	  return ("ready");
    }

    return ("wait");
}
exit( not print( main( "$FindBin::Bin/../../etc/export.cnf", ) ) );
